import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class CreateAccountPage extends StatelessWidget {
  const CreateAccountPage({super.key});


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Create Account',
      theme: ThemeData(
        scaffoldBackgroundColor: const Color.fromARGB(255, 255, 255, 255),
      ),
      home: Scaffold(
        body: ListView(children: [
          CreateAccount(),
        ]),
      ),
    );
  }
}

class CreateAccount extends StatefulWidget{
  const CreateAccount({super.key});

  @override
  State<CreateAccount> createState()=> _CreateAccountState();
}

class _CreateAccountState extends State<CreateAccount> {
 
 //Controller for text inputs
  final TextEditingController emailController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();  
  final TextEditingController firstNameController = TextEditingController();
  final TextEditingController lastNameController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1280,
          height: 832,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 394,
                top: 70,
                child: SizedBox(
                  width: 504,
                  height: 78,
                  child: Text(
                    'Create Account',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 64,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 229,
                child: SizedBox(
                  width: 667,
                  height: 60,
                  //TextField input for First Name input
                  child: TextField(
                    controller: firstNameController,
                    keyboardType: TextInputType.text,
                    decoration: InputDecoration(
                      filled: true,
                      fillColor: Color(0xFFD9D9D9),
                      border: OutlineInputBorder(),
                      hintText: 'John',
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 185,
                child: Text(
                  'First Name',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 36,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 333,
                //TextField for Last Name input
                child: SizedBox(
                  width: 667,
                  height: 60,
                  child: TextField(
                    controller: lastNameController,
                    keyboardType: TextInputType.text,
                    decoration: InputDecoration(
                      filled: true,
                      fillColor: Color(0xFFD9D9D9),
                      border: OutlineInputBorder(),
                      hintText: 'Doe',
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 289,
                child: Text(
                  'Last Name',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 36,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 437,
                //TextField for email input
                child: SizedBox(
                  width: 667,
                  height: 60,
                  child: TextField(
                    controller: emailController,
                    keyboardType: TextInputType.emailAddress,
                    decoration: InputDecoration(
                      filled: true,
                      fillColor: Color(0xFFD9D9D9),
                      border: OutlineInputBorder(),
                      hintText: 'example@email.com',
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 393,
                child: Text(
                  'E-Mail',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 36,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 541,
                child: SizedBox(
                  width: 667,
                  height: 60,
                //TextField for password input
                  child: TextField(
                    controller: passwordController,
                    keyboardType: TextInputType.visiblePassword,
                    decoration: InputDecoration(
                      filled: true,
                      fillColor: Color(0xFFD9D9D9),
                      border: OutlineInputBorder(),
                      hintText: 'Password',
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 497,
                child: Text(
                  'Password',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 36,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 536,
                top: 645,
                child: Container(
                  width: 247,
                  height: 68,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 536,
                top: 665,
                child: SizedBox(
                  width: 247,
                  height: 29,
                  child: Text(
                    'Sign-Up',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}