// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
//   );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0jmsPzCfMARC-UvwBC6pT1r260ZIC-l8',
    appId: '1:721359447910:web:a1c4e06d6a5f7978958aa7',
    messagingSenderId: '721359447910',
    projectId: 'adventra-490ff',
    authDomain: 'adventra-490ff.firebaseapp.com',
    storageBucket: 'adventra-490ff.firebasestorage.app',
    measurementId: 'G-SWN3V62H42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qSVdu77EUCUR18-1KSP14EjVsyGOAFA',
    appId: '1:721359447910:android:c88f0b7e1660bf7d958aa7',
    messagingSenderId: '721359447910',
    projectId: 'adventra-490ff',
    storageBucket: 'adventra-490ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkNH_nr1Rz52AKA3AYGH2ghnCtCGyTjXc',
    appId: '1:721359447910:ios:60ef07c2738bb056958aa7',
    messagingSenderId: '721359447910',
    projectId: 'adventra-490ff',
    storageBucket: 'adventra-490ff.firebasestorage.app',
    iosBundleId: 'com.example.swe6733Group3Adventura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkNH_nr1Rz52AKA3AYGH2ghnCtCGyTjXc',
    appId: '1:721359447910:ios:60ef07c2738bb056958aa7',
    messagingSenderId: '721359447910',
    projectId: 'adventra-490ff',
    storageBucket: 'adventra-490ff.firebasestorage.app',
    iosBundleId: 'com.example.swe6733Group3Adventura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0jmsPzCfMARC-UvwBC6pT1r260ZIC-l8',
    appId: '1:721359447910:web:f6942b34776a1ec7958aa7',
    messagingSenderId: '721359447910',
    projectId: 'adventra-490ff',
    authDomain: 'adventra-490ff.firebaseapp.com',
    storageBucket: 'adventra-490ff.firebasestorage.app',
    measurementId: 'G-4PZSE921LT',
  );
}
